name: aayutrack
description: AAYUTRACK – Digital Compliance & Remote Patient Monitoring Platform
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.8

  # State Management
  flutter_riverpod: ^2.5.1

  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
