// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjfuGdLehUgMadBAAbMmGx_A8Dppcgt7o',
    appId: '1:969513127632:web:fafa9d50361745a9e958d5',
    messagingSenderId: '969513127632',
    projectId: 'aayutrack-f949a',
    authDomain: 'aayutrack-f949a.firebaseapp.com',
    databaseURL: 'https://aayutrack-f949a-default-rtdb.firebaseio.com',
    storageBucket: 'aayutrack-f949a.firebasestorage.app',
    measurementId: 'G-HD34MYE5KP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTLYYfIdKMQm9XU0tEHNLB3vkeqvB_WWE',
    appId: '1:969513127632:android:449e2530afce9c4fe958d5',
    messagingSenderId: '969513127632',
    projectId: 'aayutrack-f949a',
    databaseURL: 'https://aayutrack-f949a-default-rtdb.firebaseio.com',
    storageBucket: 'aayutrack-f949a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAd--XZmqxf3yG-E49XNn3KlyNG7pU5E4M',
    appId: '1:969513127632:ios:750b41a3aad408a0e958d5',
    messagingSenderId: '969513127632',
    projectId: 'aayutrack-f949a',
    databaseURL: 'https://aayutrack-f949a-default-rtdb.firebaseio.com',
    storageBucket: 'aayutrack-f949a.firebasestorage.app',
    iosClientId: '969513127632-2l6esjepp7jqqm440h4efqjra90tl034.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAd--XZmqxf3yG-E49XNn3KlyNG7pU5E4M',
    appId: '1:969513127632:ios:750b41a3aad408a0e958d5',
    messagingSenderId: '969513127632',
    projectId: 'aayutrack-f949a',
    databaseURL: 'https://aayutrack-f949a-default-rtdb.firebaseio.com',
    storageBucket: 'aayutrack-f949a.firebasestorage.app',
    iosClientId: '969513127632-2l6esjepp7jqqm440h4efqjra90tl034.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjfuGdLehUgMadBAAbMmGx_A8Dppcgt7o',
    appId: '1:969513127632:web:af3c5658b89eb7e8e958d5',
    messagingSenderId: '969513127632',
    projectId: 'aayutrack-f949a',
    authDomain: 'aayutrack-f949a.firebaseapp.com',
    databaseURL: 'https://aayutrack-f949a-default-rtdb.firebaseio.com',
    storageBucket: 'aayutrack-f949a.firebasestorage.app',
    measurementId: 'G-G27YMMT0KK',
  );
}
