name: aayutrack
description: AAYUTRACK healthtech auth module
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  cloud_firestore: ^6.1.3
  firebase_auth: ^6.2.0
  firebase_core: ^4.5.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.3.1
  google_fonts: ^6.2.1
  google_sign_in: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true